version: '4.2'

services:
  #  spring-boot-tb:
  #    depends_on:
  #      - spring-boot-tb-db
  #    build:
  #      context: .
  #    environment:
  #      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
  #    restart: always

  spring-boot-tb-db:
    image: mysql:8.0.37-debian
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dev_spring_boot_tb_db"
      # Password for root access
      MYSQL_ROOT_PASSWORD: 12345 #or use ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: user           #or use ${MYSQL_USER}
      MYSQL_PASSWORD: 12345      #or use ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      # Opens port 3306 on the container
      - '3306'

  phpmyadmin:
    image: phpmyadmin:5.1.3
    container_name: PhpMyAdmin
    restart: always
    links:
      - spring-boot-tb-db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=spring-boot-tb-db
      - MYSQL_ROOT_PASSWORD=12345

volumes:
  mysql-data:
